export const ADD_TO_CART = "ADD_TO_CARD";
export const UPDATE_PLUS_PRODUCT_IN_CART = "UPDATE_PLUS_PRODUCT_IN_CART";
export const UPDATE_MINUS_PRODUCT_IN_CART = "UPDATE_MINUS_PLUS_PRODUCT_IN_CART";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
